version: "3.8"
services:
  redis:
    image: redis:7-alpine
    container_name: flashbattle_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1"]
  app:
    build: .
    container_name: flashbattle_app
    ports:
      - "3000:3000"
    depends_on:
      - redis
